//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hunarmis.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Hunar_DBEntities : DbContext
    {
        public Hunar_DBEntities()
            : base("name=Hunar_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<tbl_UserLogin> tbl_UserLogin { get; set; }
        public virtual DbSet<Benefit_Master> Benefit_Master { get; set; }
        public virtual DbSet<JobEmployed_Master> JobEmployed_Master { get; set; }
        public virtual DbSet<LocatedKM_Master> LocatedKM_Master { get; set; }
        public virtual DbSet<tbl_MailData> tbl_MailData { get; set; }
        public virtual DbSet<tbl_Participant_Calling> tbl_Participant_Calling { get; set; }
        public virtual DbSet<QuestionBook> QuestionBooks { get; set; }
        public virtual DbSet<QuestionOption> QuestionOptions { get; set; }
        public virtual DbSet<FormMaster> FormMasters { get; set; }
        public virtual DbSet<tbl_Mapped> tbl_Mapped { get; set; }
        public virtual DbSet<tbl_MappedTrainCenter> tbl_MappedTrainCenter { get; set; }
        public virtual DbSet<tbl_ParticipantRemarks_History> tbl_ParticipantRemarks_History { get; set; }
        public virtual DbSet<tbl_FileUpload> tbl_FileUpload { get; set; }
        public virtual DbSet<Tbl_ExceptionHandle> Tbl_ExceptionHandle { get; set; }
        public virtual DbSet<tbl_LogBatchTrainer> tbl_LogBatchTrainer { get; set; }
        public virtual DbSet<tbl_AttendParticipant> tbl_AttendParticipant { get; set; }
        public virtual DbSet<SessionPlanTopic_Master> SessionPlanTopic_Master { get; set; }
        public virtual DbSet<tbl_AttendPartTopic> tbl_AttendPartTopic { get; set; }
        public virtual DbSet<tbl_AssessmentSchedule> tbl_AssessmentSchedule { get; set; }
        public virtual DbSet<tbl_SendMail> tbl_SendMail { get; set; }
        public virtual DbSet<tbl_AssessmentSendLinkEmail> tbl_AssessmentSendLinkEmail { get; set; }
        public virtual DbSet<tbl_Survey> tbl_Survey { get; set; }
        public virtual DbSet<tbl_SurveyAnswer> tbl_SurveyAnswer { get; set; }
        public virtual DbSet<AnnualHousehold_Master> AnnualHousehold_Master { get; set; }
        public virtual DbSet<Courses_Master> Courses_Master { get; set; }
        public virtual DbSet<District_Master> District_Master { get; set; }
        public virtual DbSet<Educational_Master> Educational_Master { get; set; }
        public virtual DbSet<EmployeeType_Master> EmployeeType_Master { get; set; }
        public virtual DbSet<FamilyMember_Master> FamilyMember_Master { get; set; }
        public virtual DbSet<IDType_Master> IDType_Master { get; set; }
        public virtual DbSet<Industry_Master> Industry_Master { get; set; }
        public virtual DbSet<KnowledgeEnglish_Master> KnowledgeEnglish_Master { get; set; }
        public virtual DbSet<Languages_Master> Languages_Master { get; set; }
        public virtual DbSet<Month_Master> Month_Master { get; set; }
        public virtual DbSet<PreTraining_Master> PreTraining_Master { get; set; }
        public virtual DbSet<State_Master> State_Master { get; set; }
        public virtual DbSet<TargetGroup_Master> TargetGroup_Master { get; set; }
        public virtual DbSet<TrainingAgency_Master> TrainingAgency_Master { get; set; }
        public virtual DbSet<TrainingCenter_Master> TrainingCenter_Master { get; set; }
        public virtual DbSet<WorkExperience_Master> WorkExperience_Master { get; set; }
        public virtual DbSet<Year_Master> Year_Master { get; set; }
        public virtual DbSet<MaritalStatus_Master> MaritalStatus_Master { get; set; }
        public virtual DbSet<tbl_AttendanceParticipant> tbl_AttendanceParticipant { get; set; }
        public virtual DbSet<Batch_Master> Batch_Master { get; set; }
        public virtual DbSet<AssetOwnership_Master> AssetOwnership_Master { get; set; }
        public virtual DbSet<tbl_Participant_Child> tbl_Participant_Child { get; set; }
        public virtual DbSet<tbl_ParticipantResumeTemplate> tbl_ParticipantResumeTemplate { get; set; }
        public virtual DbSet<tbl_ExcelParticipantData> tbl_ExcelParticipantData { get; set; }
        public virtual DbSet<tbl_PlacementTracker> tbl_PlacementTracker { get; set; }
        public virtual DbSet<tbl_Participant> tbl_Participant { get; set; }
    }
}
