//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hunarmis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SessionPlanTopic_Master
    {
        public int SessionPlanTPId_pk { get; set; }
        public string Title { get; set; }
        public string Methodology { get; set; }
        public string DurationMinutes { get; set; }
        public string SESSIONPlanType { get; set; }
        public string DAYWise { get; set; }
        public Nullable<int> CourseId { get; set; }
        public string CourseName { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    }
}
