//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hunarmis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_AttendPartTopic
    {
        public System.Guid AttendanceTopicId_pk { get; set; }
        public Nullable<System.Guid> AttendanceId_fk { get; set; }
        public Nullable<int> CouresId { get; set; }
        public Nullable<int> TopicId { get; set; }
        public string TopicOther { get; set; }
        public Nullable<bool> AttendTopicIsActive { get; set; }
        public string AttendTopicCreatedBy { get; set; }
        public Nullable<System.DateTime> AttendTopicCreatedOn { get; set; }
    }
}
