//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hunarmis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_MappedTrainCenter
    {
        public System.Guid TrainCenterMappedId_pk { get; set; }
        public Nullable<System.Guid> MappedId_fk { get; set; }
        public Nullable<int> DistrictId { get; set; }
        public Nullable<int> TrainingAgencyId { get; set; }
        public Nullable<int> TrainingCenterId { get; set; }
    }
}
