//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hunarmis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_AssessmentSendLinkEmail
    {
        public System.Guid AssessmentSendLinkPartId_pk { get; set; }
        public Nullable<System.Guid> AssessmentScheduleId_fk { get; set; }
        public Nullable<System.Guid> ParticipantId_fk { get; set; }
        public Nullable<System.Guid> RandomValue { get; set; }
        public string AssessmentLink { get; set; }
        public Nullable<int> BatchId { get; set; }
        public Nullable<System.DateTime> ExamDate { get; set; }
        public Nullable<System.TimeSpan> ExamStartTime { get; set; }
        public Nullable<System.TimeSpan> ExamEndTime { get; set; }
        public string Password { get; set; }
        public Nullable<bool> AssessmentSchedule { get; set; }
        public Nullable<int> IsEmailSend { get; set; }
        public Nullable<int> NoofAttempt { get; set; }
        public Nullable<System.DateTime> AttemptDt { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    }
}
