//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hunarmis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_AttendParticipant
    {
        public System.Guid AttendancePartId_pk { get; set; }
        public Nullable<System.Guid> AttendanceId_fk { get; set; }
        public Nullable<System.Guid> ParticipantId_fk { get; set; }
        public Nullable<bool> AttendPartIsActive { get; set; }
        public string AttendPartCreatedBy { get; set; }
        public Nullable<System.DateTime> AttendPartCreatedOn { get; set; }
    }
}
