//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hunarmis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ExcelParticipantData
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> ParticipantID_fk { get; set; }
        public string StateName { get; set; }
        public string DistrictName { get; set; }
        public string Name { get; set; }
        public string Gender { get; set; }
        public string DateofBirth { get; set; }
        public string Age { get; set; }
        public string PhoneNo { get; set; }
        public string EmailID { get; set; }
        public string AadharCardNo { get; set; }
        public string BatchName { get; set; }
        public string BatchStartDate { get; set; }
        public string BatchEndDate { get; set; }
        public string AssessmentScore { get; set; }
        public string QualificationName { get; set; }
        public string EduQualOther { get; set; }
        public string CourseName { get; set; }
        public string TrainingAgencyName { get; set; }
        public string TrainingCenter { get; set; }
        public string TrainerName { get; set; }
        public string TrainerMobileNo { get; set; }
        public string IsPlaced { get; set; }
        public string DOBDD { get; set; }
        public string DOBMM { get; set; }
        public string DOBYYYY { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string MaritalStatus { get; set; }
        public string NoofFamilyMembers { get; set; }
        public Nullable<decimal> AnnualHouseholdincome { get; set; }
        public string PreTrainingStatus { get; set; }
        public string TargetGroup { get; set; }
    }
}
