//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hunarmis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SendMail
    {
        public System.Guid Id { get; set; }
        public Nullable<int> Batch_Id { get; set; }
        public Nullable<System.Guid> AssessmentId { get; set; }
        public Nullable<System.Guid> ParticipantId { get; set; }
        public string MFrom { get; set; }
        public string MTo { get; set; }
        public string ToOtherMail { get; set; }
        public string Subject { get; set; }
        public string Boby { get; set; }
        public string ReceiverName { get; set; }
        public string SenderName { get; set; }
        public Nullable<bool> IsSented { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ExtraCol1 { get; set; }
        public string ExtraCol2 { get; set; }
    }
}
