//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hunarmis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Participant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Participant()
        {
            this.tbl_PlacementTracker = new HashSet<tbl_PlacementTracker>();
        }
    
        public System.Guid ID { get; set; }
        public string RegID { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string FullName { get; set; }
        public string Gender { get; set; }
        public string Age { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string DateOfBirth { get; set; }
        public string PhoneNo { get; set; }
        public string AlternatePhoneNo { get; set; }
        public string EmailID { get; set; }
        public string AadharCardNo { get; set; }
        public Nullable<int> BatchId { get; set; }
        public string AssessmentScore { get; set; }
        public Nullable<int> EduQualificationID { get; set; }
        public string EduQualOther { get; set; }
        public Nullable<int> CourseEnrolledID { get; set; }
        public Nullable<int> StateID { get; set; }
        public Nullable<int> DistrictID { get; set; }
        public Nullable<int> TrainingAgencyID { get; set; }
        public Nullable<int> TrainingCenterID { get; set; }
        public string TrainerName { get; set; }
        public string TrainerMobileNo { get; set; }
        public Nullable<System.Guid> TrainerId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsPlaced { get; set; }
        public Nullable<bool> IsOffered { get; set; }
        public Nullable<int> CallTempStatus { get; set; }
        public Nullable<System.DateTime> CallTempStatusDate { get; set; }
        public string CallTempReportedBy { get; set; }
        public string CallRemark { get; set; }
        public Nullable<int> CallMonth { get; set; }
        public Nullable<int> CallYear { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> FixedCallLimitMonth { get; set; }
        public Nullable<int> AtPresentCallStatus { get; set; }
        public string RemarkStatus { get; set; }
        public Nullable<System.DateTime> RemarkDate { get; set; }
        public string RemarkReportedBy { get; set; }
        public Nullable<System.Guid> RemarksID_fk { get; set; }
        public Nullable<System.Guid> CallingID_fk { get; set; }
        public Nullable<bool> IsAssessmentDone { get; set; }
        public string MaritalStatus { get; set; }
        public Nullable<int> NoofFamilyMembers { get; set; }
        public Nullable<decimal> AnnualHouseholdincome { get; set; }
        public Nullable<int> PreTrainingStatus { get; set; }
        public Nullable<int> TargetGroup { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_PlacementTracker> tbl_PlacementTracker { get; set; }
    }
}
