//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hunarmis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Participant_Calling
    {
        public System.Guid ID { get; set; }
        public Nullable<int> QuesMonth { get; set; }
        public Nullable<int> QuesYear { get; set; }
        public string IsCalling { get; set; }
        public Nullable<System.DateTime> CallingDate { get; set; }
        public string Remark { get; set; }
        public Nullable<System.Guid> ParticipantId_fk { get; set; }
        public string IsAssessmentCert { get; set; }
        public string IsPresent { get; set; }
        public string IsComfortable { get; set; }
        public string EmpCompany { get; set; }
        public string FirstJobTraining { get; set; }
        public Nullable<System.DateTime> DOJ { get; set; }
        public string CurrentEmployer { get; set; }
        public string Designation { get; set; }
        public string SalaryPackage { get; set; }
        public string CurrentlyWorking { get; set; }
        public Nullable<int> WorkingKM { get; set; }
        public string WorkingKMOther { get; set; }
        public string Traininghelp { get; set; }
        public string SalaryWages { get; set; }
        public string ExpectationJobRole { get; set; }
        public string WorkPlaceSafe { get; set; }
        public string IsMSBenefit { get; set; }
        public Nullable<int> MSBenefitId { get; set; }
        public string MSOther { get; set; }
        public string AnyChallenges { get; set; }
        public string AreaSupport { get; set; }
        public Nullable<int> EmployedId { get; set; }
        public string EmployedOther { get; set; }
        public string IsGettingjob { get; set; }
        public string PlacedStatus { get; set; }
        public Nullable<bool> Is_Offered { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    }
}
